apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-voting-app
    name: result-service
  name: result-service
spec:
  ports:
  - nodePort: 30004
    port: 80
    targetPort: 80
  selector:
    app: demo-voting-app
    name: result-app-pod
  type: NodePort
